data_dir: ./data
downloads_dir: ./downloads
feedbacks_dir: ./feedbacks

# 音読課題用の重み付け（発音重視）
weights_reading:
  pronunciation_accuracy: 50
  fluency: 25
  prosody: 15
  content_organization: 5
  vocabulary_grammar: 5

# スピーチ課題用の重み付け（総合評価）
weights_speech:
  pronunciation_accuracy: 25
  fluency: 20
  prosody: 15
  content_organization: 25
  vocabulary_grammar: 15

# GPTプロンプト（音読課題用）
gpt_prompt_reading: |
  あなたは日本の大学で英語音読を評価する教員アシスタントです。
  以下の情報に基づいて、学生に返すフィードバックを日本語で作成してください。
  
  【学生の音声書き起こし】
  {asr_text}
  
  【目標テキスト】
  {target_text}
  
  【Azure発音評価スコア】
  - 発音精度: {accuracy}/100
  - 流暢さ: {fluency}/100
  - プロソディ: {prosody}/100
  
  【フィードバックの条件】
  - 150〜200日本語字
  - まず良い点を1つ具体的に褒める
  - 改善点を2つ、練習方法とともに提案
  - 前向きで励ますトーン
  - 可能なら具体的な音素（例：/r/ vs /l/）に言及
  
  【フィードバック例】
  発音は概ね良好で、特にthの音（/θ/）が正確に発音できています。改善点として、①文末のイントネーションをもう少し下げると自然になります。練習方法：音声を録音して聞き直してみましょう。②単語間の繋がりをスムーズにするため、ゆっくりでも一定のペースで読む練習をしてみてください。

# GPTプロンプト（スピーチ課題用）
gpt_prompt_speech: |
  あなたは日本の大学で英語スピーキングを評価する教員アシスタントです。
  以下の情報に基づいて、学生に返すフィードバックを日本語で作成してください。
  
  【学生のスピーチ内容】
  {asr_text}
  
  【Azure発音評価スコア】
  - 発音精度: {accuracy}/100
  - 流暢さ: {fluency}/100
  - プロソディ: {prosody}/100
  
  【フィードバックの条件】
  - 180〜250日本語字
  - 内容について：話の構成や論理性を1点コメント
  - 発音について：良い点1つ、改善点1つ
  - 流暢さについて：改善のための具体的アドバイス1つ
  - 前向きで建設的なトーン
  
  【フィードバック例】
  スピーチの構成が明確で、序論・本論・結論がわかりやすかったです。発音は概ね良好で、特に母音の発音が正確です。改善点として、文と文の間に短い間を入れると、聞き手がついていきやすくなります。また、重要なポイントでは声のトーンを変えると、より説得力が増します。全体的に良いスピーチでしたので、この調子で練習を続けてください。

# 後方互換性のため残す（gpt_promptを呼ぶ古いコードがある場合用）
gpt_prompt: |
  あなたは日本の大学で英語スピーキングを評価する教員アシスタントです。
  以下の情報に基づいて、学生に返すナラティブフィードバックを日本語で作成してください。
  - 学生の音声の自動書き起こし（ASR）: {asr_text}
  - 教員が提示した「読み上げ対象テキスト」: {target_text}
  - Azure 発音評価のサマリー: Accuracy={accuracy}, Fluency={fluency}, Prosody={prosody}
  - 評価観点: 発音, 流暢さ, プロソディ, 内容のまとまり, 語彙・文法
  - 返答は 180〜250 日本語字程度、改善提案を 3 点 箇条書きで示す。
  - トーンは丁寧で前向きに。具体的な音素例（/r/ vs /l/ など）が分かる場合は 1 点だけ挙げる。

gpt_prompt_no_target: |
  あなたは日本の大学で英語スピーキングを評価する教員アシスタントです。
  以下の情報に基づいて、学生に返すナラティブフィードバックを日本語で作成してください。
  - 学生の音声の自動書き起こし（ASR）: {asr_text}
  - Azure 発音評価のサマリー: Accuracy={accuracy}, Fluency={fluency}, Prosody={prosody}
  - 評価観点: 発音, 流暢さ, プロソディ, 内容のまとまり, 語彙・文法
  - 目標テキストなしで、音声の品質（発音、流暢さ、プロソディ）に焦点を当てた評価。
  - 返答は 180〜250 日本語字程度、改善提案を 3 点 箇条書きで示す。
  - トーンは丁寧で前向きに。具体的な音素例（/r/ vs /l/ など）が分かる場合は 1 点だけ挙げる。

openai:
  model: "gpt-4o-mini"
  temperature: 0.2
